import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./styles/theme-provider";

import Navbar from "./components/Navbar";

// Fonts
const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// Metadata
export const metadata: Metadata = {
  title: "Productivity Suite 1.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body
          className={`
          ${ibmPlexMono.className} 
          ${geist.variable} 
          ${geistMono.variable} 
          antialiased
        `}
        >
          <main className="w-full min-h-screen app-theme">
            <Navbar />

            <div className="border-t-2 border-[#231f1a]/70 bg-transparent">
              <div className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6">
                {children}
              </div>
            </div>
          </main>
        </body>
      </ThemeProvider>
    </html>
  );
}
