import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";

// Fonts
const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// Metadata
export const metadata: Metadata = {
  title: "Productivity Suite 1.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${ibmPlexMono.className} 
          ${geist.variable} 
          ${geistMono.variable} 
          antialiased 
          bg-[#e6e3de]
        `}
      >
        <main className="w-full min-h-screen">
          <Navbar />

          <div className="bg-[#ece9e4] border-t-2 border-black">
            <div className="py-6">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
